[package]
name = "MathPlus"
version = "1.0.0"
edition = "2024"

[dependencies]
egui = "0.27"
eframe = "0.27"
meval = "0.2.0"

[profile.release]
opt-level = "z"

[[bin]]
name = "rust_calculator"
path = "src/main.rs"